# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 03:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('buy_value', models.IntegerField(default=0)),
                ('sell_value', models.IntegerField(default=0)),
                ('slots_required', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('defense_value', models.IntegerField(default=2)),
                ('type', models.TextField(default=b'armor', editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('name', models.TextField(default=b'The Stranger')),
                ('hpmax', models.IntegerField(default=51)),
                ('current_hp', models.IntegerField()),
                ('base_attack', models.IntegerField(default=3)),
                ('base_defense', models.IntegerField(default=3)),
                ('gold', models.IntegerField(default=50)),
                ('xp', models.IntegerField(default=0)),
                ('renown', models.IntegerField(default=0)),
                ('next_levelup', models.IntegerField(default=100)),
                ('num_armor', models.IntegerField(default=0)),
                ('fights_won', models.IntegerField(default=0)),
                ('fights_lost', models.IntegerField(default=0)),
                ('dead', models.BooleanField(default=False)),
                ('times_died', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=b'An Enemy!')),
                ('xp_value', models.IntegerField(default=5)),
                ('renown_value', models.IntegerField(default=10)),
                ('hpmax', models.IntegerField(default=100)),
                ('current_hp', models.IntegerField(default=0)),
                ('base_attack', models.IntegerField(default=4)),
                ('base_defense', models.IntegerField(default=5)),
                ('gold', models.IntegerField(default=22)),
                ('dead', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField(default=10)),
                ('slots_filled', models.IntegerField(default=0)),
                ('slots_empty', models.IntegerField(default=10)),
                ('character', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='arenafighter.Character')),
            ],
            options={
                'verbose_name_plural': 'inventories',
            },
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('buy_value', models.IntegerField(default=0)),
                ('sell_value', models.IntegerField(default=0)),
                ('slots_required', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('heal_percent', models.IntegerField(default=20)),
                ('type', models.TextField(default=b'potion', editable=False)),
                ('inventory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='potion', to='arenafighter.Inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_character', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='arenafighter.Character')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('buy_value', models.IntegerField(default=0)),
                ('sell_value', models.IntegerField(default=0)),
                ('slots_required', models.IntegerField(default=1)),
                ('equipped', models.BooleanField(default=False)),
                ('attack_value', models.IntegerField(default=2)),
                ('type', models.TextField(default=b'weapon', editable=False)),
                ('inventory', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weapon', to='arenafighter.Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_characters', to='arenafighter.Profile'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipped_armor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipped_on', to='arenafighter.Armor'),
        ),
        migrations.AddField(
            model_name='armor',
            name='inventory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='armor', to='arenafighter.Inventory'),
        ),
    ]
